routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WebsiteController@index');
Route::get('/index1', 'WebsiteController@index1');
Route::get('/about', 'WebsiteController@about');
Route::get('/ncert', 'WebsiteController@ncert');
Route::get('/pricing', 'WebsiteController@pricing');
Route::get('/contact', 'WebsiteController@contact');
Route::get('/privacypolicy', 'WebsiteController@privacypolicy');

//ADMIN PANEL
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
  Route::resource('membership','Admin\MembershipController');
  Route::resource('client','Admin\ClientController');

// Route::get('/dashboard', 'AdminController@dashboard');
// Route::get('/all_courses', 'AdminController@all_courses');
// Route::get('/add_course', 'AdminController@add_course');
// Route::get('/edit_course', 'AdminController@edit_course');
// Route::get('/formfields', 'AdminController@formfields');
});



// admin routing start here

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreemployeeRequest;
use App\Http\Requests\Admin\UpdateemployeeRequest;
use App\ConfRoom;


class ClientController extends Controller
{
    /**
     * Display a listing of Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        $users = DB::table('users')->Where('role_id','!=','1')
            ->get();
        return view('admin.client.index',compact('users'));
    }

    /**
     * Show the form for creating new Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        return view('admin.client.create');
    }

    /**
     * Store a newly created Role in storage.
     *
     * @param  \App\Http\Requests\StoreemployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // dd($request);
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
           if($request->type == 'update'){
             $user = User::find($request->userid);
             $user->fnm = $request->fnm;
             $user->lnm = $request->lnm;
             $user->mobile = $request->mobile;
             $user->save();
             $cmp = \App\Company::find($request->cmpid);
             $cmp->cmpnm = $request->cmpnm;
             $cmp->mobile = $request->mobile;
             $cmp->billtype = $request->billtype;
             $cmp->roomstrength = $request->roomstrength;
             $cmp->pulserate = $request->pulserate;
             $cmp->dialinpulserate = $request->dialinpulserate;
             $cmp->portrate = $request->portrate;
             $cmp->save();
             $address = \App\Address::where('cmpid', $request->cmpid)->first();
             $address->address = $request->address;
             $address->city = $request->city;
             $address->state = $request->state;
             $address->pincode = $request->pincode;
             $address->pannumber = $request->pannumber;
             $address->save();
             return redirect()->back();

           }else{
             $cmp = \App\Company::findOrFail($request->cmpid);
             $request['active'] = 1;
             $cmp->update($request->all());
             $users = User::whereIn('role_id',[2,3])->where('cmpid',$cmp->id)->first();
             if($users){
               \Mail::to($users->email)->send(new \App\Mail\SubcriptionNotification($users,$cmp));
             }
             return redirect()->route('admin.client.index');
           }
    }


    public function edit($id)
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        $users =  User::find($id);
        $address = \App\Address::where('userid', $id)->first();

        return view('admin.client.edit',compact('users','address'));
    }

    public function update(Request $request, $id)
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        dd($id);
        return redirect()->route('admin.client.index');
    }


    public function show($id)
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        $users =  User::find($id);
        $address = \App\Address::where('userid', $id)->first();

        return view('admin.client.edit',compact('users','address'));
    }

    public function destroy($id)
    {
        if (! Gate::allows('admin_access')) {
            return abort(401);
        }
        dd($id);
        $user = \App\User::findOrFail($id);
        $user->blckflg = true;
        $user->save();
        return redirect()->route('admin.client.index');
    }


}

resources/views/admin/client/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">User List</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="/">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li><a class="parent-item" href="admin/client">Users</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
  <form class="" action="{{ route('admin.client.store') }}" method="post">
    @csrf()
    <h4 class="center purple">Profile</h4>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-user" aria-hidden="true"></i> <br>
        <b>Name:</b> <br>
        <input type="text" class="form-control" name="fnm" value="{{isset($users->fnm)?$users->fnm:''}}">
      </div>
    <!-- </div>
    <div class="row center m-4"> -->
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-mobile" aria-hidden="true"></i> <br>
        <b>Mobile:</b> <br>
        <input type="text" class="number form-control" name="mobile" value="{{isset($users->mobile)?$users->mobile:''}}">
      </div>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-envelope" aria-hidden="true"></i> <br>
        <b>Email:</b> <br>
        <input type="text" readonly class="form-control" name="email" value="{{isset($users->email)?$users->email:''}}">
      </div>
    </div>

    <!-- <hr> -->
    <h4 class="center purple">Address</h4>
    <div class="row center m-4">
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>Address:</b> <br>
        <input type="text" class="form-control" name="address" value="{{isset($address->address)?$address->address:''}}">
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>City:</b> <br>
        <input type="text" class="form-control" name="city" value="{{isset($address->city)?$address->city:''}}">
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>State:</b> <br>
        <input type="text" class="form-control" name="state" value="{{isset($address->state)?$address->state:''}}">
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>Pincode:</b> <br>
        <input type="text" class="form-control" name="pincode" value="{{isset($address->pincode)?$address->pincode:''}}">
      </div>
    </div>


      </div>
    </div>
  </div>
</div>


@endsection

resources/views/admin/client/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">User List</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="/">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					<li><a class="parent-item" href="admin/client">Users</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">

        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <th>Mobile</th>
              <th>Email</th>
              <th>User Type</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($users as $key => $value)
            <tr>
              <td>{{$value->name}}</td>
              <td>{{$value->mobile}}</td>
              <td>{{$value->email}}</td>
              @if($value->role_id==2)
              <td>Teacher</td>
              @else
              <td>Student</td>
              @endif
              <td>
                <a href="{{ route('admin.client.show',[$value->id]) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                <a href="{{ route('admin.client.edit',[$value->id]) }}"><i class="fa fa-gear" aria-hidden="true"></i></a>
                <a href="{{ route('admin.client.destroy',[$value->id]) }}"><i class="fa fa-ban" aria-hidden="true"></i></a>
              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
    </div>
    </div>
@endsection

resources/views/admin/client/show.blade.php
@extends('layouts.admin')

@section('content')
<link rel="stylesheet" href="/css/adminpanel/common_admin.css">
<link rel="stylesheet" href="/css/adminpanel/verification.css">

<div class="pg-verification">
  <div class="left_section">
    <dl>
      <dt>
        <img src="{{ asset('images/panel/tabs/profile.png') }}" alt="Whistling" width="30" />
        {{ Auth::user()->fnm }}
        <span class="purple"><?php echo date("d-M-Y"); ?></span>
      </dt>
      <dd>
        {{\App\Role::where('id',\Auth::user()->role_id)->first()->title}} <br> ID: #BIO{{1000+ \Auth::user()->id}}

      </dd>
    </dl>
  </div>

  <div class="right_section">

    <h3 class="center purple">Profile</h3>

    <div class="row center m-4">
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-building" aria-hidden="true"></i> <br>
        <b>Company:</b> <br>
        {{ $company->cmpnm }}
      </div>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-credit-card" aria-hidden="true"></i> <br>
        <b>GST Number:</b> <br>
        {{ $address->pannumber }}
      </div>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-user" aria-hidden="true"></i> <br>
        <b>Name:</b> <br>
        {{ $users->fnm }} {{ $users->lnm }}
      </div>
    </div>
    <div class="row center m-4">
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-mobile" aria-hidden="true"></i> <br>
        <b>Mobile:</b> <br>
        {{ $users->mobile }}
      </div>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <i class="fa fa-envelope" aria-hidden="true"></i> <br>
        <b>Email:</b> <br>
        {{ $users->email }}
      </div>
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        @if($company->emailverify == 1)
          <i class="fa fa-envelope" aria-hidden="true"></i> <br>
          <b>Email Verified:</b> <br>
          True
        @endif
      </div>
    </div>

    <hr>
    <h3 class="center purple">Address</h3>
    <div class="row center m-4">
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>Address:</b> <br>
        {{ $address->address }}
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>City:</b> <br>
        {{ $address->city }}
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>State:</b> <br>
        {{ $address->state }}
      </div>
      <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <i class="fa fa-map-marker" aria-hidden="true"></i><br>
        <b>Pincode:</b> <br>
        {{ $address->pincode }}
      </div>
    </div>

    <hr>
    <div class="row center m-4">
      <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <a href="{{ $address->panupload }}" target="_blank">
          <img src="{{ asset('images/panel/participant/download.png') }}" alt="Whistling" width="30"> Download GST Certificate
        </a>
      </div>
      <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <a href="{{ $address->cmplogoupload }}" target="_blank">
          <img src="{{ asset('images/panel/participant/download.png') }}" alt="Whistling" width="30"> Download Company Logo
        </a>
      </div>
    </div>
    <hr>
    <h4 class="center purple">Conference Rooms</h4>
    <div class="row center m-4">
     <table class="table table-striped">
       <thead class="thead-dark">
         <tr>
           <th>Room Name</th>
           <th>Channel/Port</th>
           <th>Assigned To</th>
         </tr>
       </thead>
       <tbody>
         @foreach ($rooms as $key => $value)
         <tr>
           <td>{{$value->name}}</td>
           <td>{{$value->channels}}</td>
           <td>{{$value->assign_to}}</td>
         </tr>
         @endforeach

       </tbody>
     </table>
    </div>

  </div>
</div>


@endsection